version: "3"

services:
    ct_api:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./ct_api:/ct_api
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
